connections:
  mypg:
    type: postgres
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: appdb
  mymysql:
    type: mysql
    host: localhost
    port: 3306
    user: root
    password: root
    database: appdb
